package com.authorizationapi.authorizationapi.repository;

import com.authorizationapi.authorizationapi.domain.AdministradorOrganizacionEncargadoDomain;
import org.springframework.data.repository.reactive.ReactiveCrudRepository;

public interface AdministradorOrganizacionEncargadoRepository extends ReactiveCrudRepository<AdministradorOrganizacionEncargadoDomain, String> {
}
